// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXAOvSnj3TNTPSVRd1TZ0gOSfzvb0Leo',
    appId: '1:527124948040:web:f292ad5349ce796180e47d',
    messagingSenderId: '527124948040',
    projectId: 'ecoti-4b5b1',
    authDomain: 'ecoti-4b5b1.firebaseapp.com',
    databaseURL: 'https://ecoti-4b5b1-default-rtdb.firebaseio.com',
    storageBucket: 'ecoti-4b5b1.appspot.com',
    measurementId: 'G-SV1TT2DNHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqOYw79CR9pg09_pP1pjoPGCmkL4IM18',
    appId: '1:527124948040:android:afc0ef4f11739ce880e47d',
    messagingSenderId: '527124948040',
    projectId: 'ecoti-4b5b1',
    databaseURL: 'https://ecoti-4b5b1-default-rtdb.firebaseio.com',
    storageBucket: 'ecoti-4b5b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY4mPMTsdEici5K1lsF0uOebZAhV_LidI',
    appId: '1:527124948040:ios:17bea4f2c15acb2e80e47d',
    messagingSenderId: '527124948040',
    projectId: 'ecoti-4b5b1',
    databaseURL: 'https://ecoti-4b5b1-default-rtdb.firebaseio.com',
    storageBucket: 'ecoti-4b5b1.appspot.com',
    iosBundleId: 'com.example.ecotiAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY4mPMTsdEici5K1lsF0uOebZAhV_LidI',
    appId: '1:527124948040:ios:fb0db1f4690114ce80e47d',
    messagingSenderId: '527124948040',
    projectId: 'ecoti-4b5b1',
    databaseURL: 'https://ecoti-4b5b1-default-rtdb.firebaseio.com',
    storageBucket: 'ecoti-4b5b1.appspot.com',
    iosBundleId: 'com.example.ecotiAppMobile.RunnerTests',
  );
}
